[package]
name = "robot"
version = "0.8.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.82"
poise = { version = "0.6.1", features = ["cache", "chrono"] }
shuttle-serenity = "0.46.0"
shuttle-runtime = "0.46.0"
shuttle-shared-db = { version = "0.46.0", default-features = false, features = ["postgres", "sqlx"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = "1.38"
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio", "tls-rustls", "chrono", "postgres", "sqlx-postgres", "bigdecimal"] }
base64 = "0.22"
regex = "1.10"
reqwest = { version = "0.12", features = ["json"] }
once_cell = "1.19"
itertools = "0.13"
rusttype = "0.9.3"
imageproc = "0.23.0"
image = "0.24.9"
stitchy-core = "0.1.2"
ics = "0.5"
uwuify = "0.2.2"
serde = "1.0.200"
deser-hjson = "2.2.4"
chrono = "0.4.34"
chrono-tz = "0.9.0"
parse_duration = "2.1.1"
percent-encoding = "2.3.1"
rand = "0.8.5"
mini-moka = "0.10.3"
