[package]
name = "wobot"
version = "1.0.1"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.95"
poise = { version = "0.6.1", features = ["cache", "chrono"] }
shuttle-serenity = "0.51.0"
shuttle-runtime = "0.51.0"
shuttle-shared-db = { version = "0.51.0", default-features = false, features = ["postgres", "sqlx"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tokio = "1.43.0"
sqlx = { version = "0.8.3", default-features = false, features = ["runtime-tokio", "tls-rustls", "chrono", "postgres", "sqlx-postgres", "bigdecimal"] }
base64 = "0.22.1"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["json"] }
itertools = "0.14.0"
ab_glyph = "0.2.29"
imageproc = "0.25.0"
image = "0.25.5"
stitchy-core = "0.1.3"
ics = "0.5"
uwuify = "0.2.2"
serde = "1.0.217"
deser-hjson = "2.2.4"
chrono = "0.4.39"
chrono-tz = "0.10.0"
parse_duration = "2.1.1"
dateparser = { version = "0.2.1", git = "https://github.com/RiediJohannes/dateparser" }
percent-encoding = "2.3.1"
rand = "0.8.5"
mini-moka = "0.10.3"
