[package]
name = "robot"
version = "0.7.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.79"
poise = { version = "0.6.1", features = ["cache", "chrono"] }
shuttle-serenity = "0.39.0"
shuttle-runtime = "0.39.0"
shuttle-secrets = "0.39.0"
shuttle-shared-db = { version = "0.39.0", default-features = false, features = ["postgres", "sqlx"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = "1.35.1"
sqlx = { version = "0.7.3", default-features = false, features = ["runtime-tokio", "tls-rustls", "chrono", "postgres", "sqlx-postgres", "bigdecimal"] }
base64 = "0.21.7"
regex = "1.10.3"
reqwest = { version = "0.11.23", features = ["tokio-rustls", "json"] }
once_cell = "1.19.0"
itertools = "0.12.0"
imageproc = "0.23.0"
rusttype = "0.9.3"
image = { version = "0.24.8", default-features = false, features = ["jpeg", "png", "gif", "rgb"] }
ics = "0.5.8"
uwuify = "0.2.2"
serde = "1.0.195"
deser-hjson = "2.2.4"
chrono = "0.4.34"
percent-encoding = "2.3.1"
chrono-tz = "0.8.6"
stitchy-core = "0.1.1"
parse_duration = "2.1.1"
rand = "0.8.5"
